Repository let-s-go-right-now/backend, pull requests merged in 2025-03, with the labels that each got.

#42 여행 지출 결과 확인하기 API 개발
  src/main/java/com/lets/go/right/now/domain/expense/dto/MemberProfileViewRes.java
  src/main/java/com/lets/go/right/now/domain/settlement/controller/SettlementController.java
  src/main/java/com/lets/go/right/now/domain/settlement/dto/TravelSettlementResult.java
  src/main/java/com/lets/go/right/now/domain/settlement/repository/TravelSettlementRepository.java
  src/main/java/com/lets/go/right/now/domain/settlement/service/SettlementService.java
  src/main/java/com/lets/go/right/now/domain/settlement/service/SettlementServiceImpl.java
Labels: :sparkles: Feat

#46 여행 정산 결과 확인하기 API 기능 추가
  src/main/java/com/lets/go/right/now/domain/settlement/dto/TravelSettlementResultReq.java
  src/main/java/com/lets/go/right/now/domain/settlement/repository/TravelSettlementRepository.java
  src/main/java/com/lets/go/right/now/domain/settlement/service/SettlementServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat

#53 여행 참여 회원별 총 지출액 계산 API 개발
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseServiceImpl.java
  src/main/java/com/lets/go/right/now/domain/settlement/controller/SettlementController.java
  src/main/java/com/lets/go/right/now/domain/settlement/dto/MemberTotalExpenseRes.java
  src/main/java/com/lets/go/right/now/domain/settlement/dto/TravelSettlementExpense.java
  src/main/java/com/lets/go/right/now/domain/settlement/service/SettlementService.java
  src/main/java/com/lets/go/right/now/domain/settlement/service/SettlementServiceImpl.java
Labels: :sparkles: Feat

#54 카테고리별 지출 리포트 보기 API 개발
  src/main/java/com/lets/go/right/now/domain/expense/controller/ExpenseController.java
  src/main/java/com/lets/go/right/now/domain/expense/dto/CategoryExpenseRes.java
  src/main/java/com/lets/go/right/now/domain/expense/dto/MemberTotalExpenseRes.java
  src/main/java/com/lets/go/right/now/domain/expense/dto/TravelTotalExpense.java
  src/main/java/com/lets/go/right/now/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseService.java
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseServiceImpl.java
  src/main/java/com/lets/go/right/now/domain/settlement/controller/SettlementController.java
  src/main/java/com/lets/go/right/now/domain/settlement/dto/TravelSettlementExpense.java
  src/main/java/com/lets/go/right/now/domain/settlement/service/SettlementService.java
  src/main/java/com/lets/go/right/now/domain/settlement/service/SettlementServiceImpl.java
Labels: :sparkles: Feat

#55 회원 별 카테고리 지출 현황 반환 API 개발
  src/main/java/com/lets/go/right/now/domain/expense/controller/ExpenseController.java
  src/main/java/com/lets/go/right/now/domain/expense/dto/MemberCategoryExpenseRes.java
  src/main/java/com/lets/go/right/now/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseService.java
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseServiceImpl.java
  src/main/java/com/lets/go/right/now/domain/settlement/repository/PersonalSpendingRepository.java
Labels: :sparkles: Feat

#57 날짜별 여행 총 지출 반환 API 개발
  src/main/java/com/lets/go/right/now/domain/expense/controller/ExpenseController.java
  src/main/java/com/lets/go/right/now/domain/expense/dto/DailyExpenseRes.java
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseService.java
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseServiceImpl.java
Labels: :sparkles: Feat

#58 CORS 설정
  src/main/java/com/lets/go/right/now/global/config/SecurityConfig.java
Labels: 🎨 Chore, :wrench: Settings

#68 회원 로그아웃 & 탈퇴 API 개발
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/dto/LeaveRes.java
  src/main/java/com/lets/go/right/now/domain/member/dto/LogoutRes.java
  src/main/java/com/lets/go/right/now/domain/member/repository/MemberRepository.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: :sparkles: Feat

#72 여행 멤버 초대 링크 생성 API 개발
  src/main/java/com/lets/go/right/now/domain/invite/controller/InviteController.java
  src/main/java/com/lets/go/right/now/domain/invite/dto/InviteLinkRes.java
  src/main/java/com/lets/go/right/now/domain/invite/service/InviteService.java
Labels: :sparkles: Feat

#73 초대 링크로 로그인 시 여행 멤버 자동 등록 API 개발
  src/main/java/com/lets/go/right/now/domain/invite/controller/InviteController.java
  src/main/java/com/lets/go/right/now/domain/invite/dto/InviteRes.java
  src/main/java/com/lets/go/right/now/domain/invite/service/InviteService.java
Labels: :sparkles: Feat

#77 회원 정보 조회 API 개발
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/dto/MemberInfoRes.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: :sparkles: Feat

#78 회원 이름 수정 API 개발
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/dto/ProfileUpdateReq.java
  src/main/java/com/lets/go/right/now/domain/member/dto/ProfileUpdateRes.java
  src/main/java/com/lets/go/right/now/domain/member/entity/Member.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: :sparkles: Feat

#80 회원 계좌번호 수정 API 개발
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/dto/ProfileUpdateRes.java
  src/main/java/com/lets/go/right/now/domain/member/entity/Member.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: :sparkles: Feat

#81 회원 프로필 이미지 수정 API 개발
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/dto/ProfileUpdateRes.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: :sparkles: Feat

#83 회원 프로필 이미지 삭제 API 개발
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: :sparkles: Feat

#84 회원 이름 수정 API 코드 리펙토링
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/dto/ProfileUpdateRes.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: 🎨 Chore

#85 회원 정보 조회 API 코드 리펙토링
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: 🎨 Chore

#86 회원 로그아웃 & 탈퇴 API 코드 리펙토링
  src/main/java/com/lets/go/right/now/domain/member/controller/MemberController.java
  src/main/java/com/lets/go/right/now/domain/member/dto/LeaveRes.java
  src/main/java/com/lets/go/right/now/domain/member/dto/LogoutRes.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberService.java
  src/main/java/com/lets/go/right/now/domain/member/service/MemberServiceImpl.java
Labels: 🎨 Chore

#87 여행 멤버 초대 링크 생성 API 코드 리펙토링 및 초대 링크 생성 방식 변경
  src/main/java/com/lets/go/right/now/domain/invite/controller/InviteController.java
  src/main/java/com/lets/go/right/now/domain/invite/dto/InviteLinkRes.java
  src/main/java/com/lets/go/right/now/domain/invite/service/InviteService.java
Labels: 🎨 Chore, :white_check_mark: Add

#88 초대 링크 토큰 관련 로직 수정
  src/main/java/com/lets/go/right/now/domain/invite/controller/InviteController.java
  src/main/java/com/lets/go/right/now/domain/invite/dto/InviteRes.java
  src/main/java/com/lets/go/right/now/domain/invite/service/InviteService.java
Labels: :white_check_mark: Add

#91 AI 추천 여행 코스 생성 API 개발
  build.gradle
  src/main/java/com/lets/go/right/now/domain/chatgpt/config/OpenAiConfig.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/controller/ChatGptController.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/ChatGptReq.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/ChatGptRes.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/EventDto.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/ItineraryDto.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/ScheduleDto.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/TransportOptionDto.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/service/ChatGptService.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/service/GooglePlacesService.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/template/PromptTemplate.java
Labels: :sparkles: Feat

#93 GTP 반환 DTO 수정
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/ChatGptRes.java
  src/main/java/com/lets/go/right/now/domain/chatgpt/service/ChatGptService.java
Labels: 🎨 Chore

#95 여행 생성시 생성한 회원을 여행 회원으로 등록
  src/main/java/com/lets/go/right/now/domain/trip/entity/TripMember.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat

#97 여행 생성 API 반환 형식 수정
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripCreateRes.java
Labels: :rotating_light: Fix, :sparkles: Feat

#99 AI 추천 여행 정보 스크랩(저장) API 개발
  src/main/java/com/lets/go/right/now/domain/member/entity/Member.java
  src/main/java/com/lets/go/right/now/domain/scrap/controller/ScrapController.java
  src/main/java/com/lets/go/right/now/domain/scrap/dto/ScrapTripReq.java
  src/main/java/com/lets/go/right/now/domain/scrap/entity/ScrappedTrip.java
  src/main/java/com/lets/go/right/now/domain/scrap/entity/ScrappedTripDetail.java
  src/main/java/com/lets/go/right/now/domain/scrap/repository/ScrapTripDetailRepository.java
  src/main/java/com/lets/go/right/now/domain/scrap/repository/ScrapTripRepository.java
  src/main/java/com/lets/go/right/now/domain/scrap/service/ScrapService.java
  src/main/java/com/lets/go/right/now/domain/trip/entity/Recommend.java
  src/main/java/com/lets/go/right/now/domain/trip/entity/ScrappedTrip.java
Labels: :sparkles: Feat

#100 스크랩 목록 조회 API 개발
  src/main/java/com/lets/go/right/now/domain/scrap/controller/ScrapController.java
  src/main/java/com/lets/go/right/now/domain/scrap/dto/ScrapTripRes.java
  src/main/java/com/lets/go/right/now/domain/scrap/repository/ScrapTripRepository.java
  src/main/java/com/lets/go/right/now/domain/scrap/service/ScrapService.java
Labels: :sparkles: Feat

#101 스크랩 상세 페이지 조회 API 개발
  src/main/java/com/lets/go/right/now/domain/scrap/controller/ScrapController.java
  src/main/java/com/lets/go/right/now/domain/scrap/dto/ScrapTripDetailRes.java
  src/main/java/com/lets/go/right/now/domain/scrap/repository/ScrapTripDetailRepository.java
  src/main/java/com/lets/go/right/now/domain/scrap/repository/ScrapTripRepository.java
  src/main/java/com/lets/go/right/now/domain/scrap/service/ScrapService.java
Labels: :sparkles: Feat

#103 특정 여행에 등록된 멤버 조회 API 개발
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripMemberListRes.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: :sparkles: Feat

#108 스크랩 삭제(해제) API 개발
  src/main/java/com/lets/go/right/now/domain/scrap/controller/ScrapController.java
  src/main/java/com/lets/go/right/now/domain/scrap/service/ScrapService.java
Labels: :sparkles: Feat

#111 특정 여행에 등록된 멤버 조회 API 삭제
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: 🎨 Chore

#113 특정 멤버 내보내기 API 개발
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
  src/main/java/com/lets/go/right/now/domain/tripMember/repository/TripMemberRepository.java
Labels: :sparkles: Feat

#117 여행 참여자 정보 조회 API 개발
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripParticipantsRes.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: :sparkles: Feat

#118 방장 권한 위임 API 개발
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/DelegateOwnerReq.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/DelegateOwnerRes.java
  src/main/java/com/lets/go/right/now/domain/trip/entity/Trip.java
  src/main/java/com/lets/go/right/now/domain/trip/entity/TripMember.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: :sparkles: Feat

#120 특정 여행에 대한 모든 지출 얻어오기
  src/main/java/com/lets/go/right/now/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/enums/SortOption.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
  src/main/java/com/lets/go/right/now/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat

#122 특정 여행 기록 상세 조회 시 반환 DTO 수정
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripDetailDto.java
  src/main/java/com/lets/go/right/now/domain/trip/entity/Trip.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: 🎨 Chore

#123 페이지, 사이즈가 반대로 전달되던 버그 해결
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat

#126 특정 여행 관리 페이지 조회 API 개발
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripInfoRes.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripMemberListRes.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
Labels: :sparkles: Feat

#127 진행 중인 여행과 이전 여행 분류 기준 수정
  src/main/java/com/lets/go/right/now/domain/trip/controller/TripController.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripListDto.java
  src/main/java/com/lets/go/right/now/domain/trip/entity/Trip.java
  src/main/java/com/lets/go/right/now/domain/trip/repository/TripRepository.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripService.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
  src/main/java/com/lets/go/right/now/domain/tripMember/repository/TripMemberRepository.java
Labels: :rotating_light: Fix

#129 스크랩 요청 DTO 및 DB 수정
  src/main/java/com/lets/go/right/now/domain/scrap/dto/ScrapTripReq.java
  src/main/java/com/lets/go/right/now/domain/scrap/entity/ScrappedTrip.java
Labels: :rotating_light: Fix

#130 start_date, end_date 모두 LocalDate 타입으로 수정
  src/main/java/com/lets/go/right/now/domain/chatgpt/dto/ChatGptReq.java
  src/main/java/com/lets/go/right/now/domain/scrap/dto/ScrapTripDetailRes.java
  src/main/java/com/lets/go/right/now/domain/scrap/dto/ScrapTripReq.java
  src/main/java/com/lets/go/right/now/domain/scrap/dto/ScrapTripRes.java
  src/main/java/com/lets/go/right/now/domain/scrap/entity/ScrappedTrip.java
Labels: 🎨 Chore

#132 Fix/#131
  src/main/java/com/lets/go/right/now/domain/expense/service/ExpenseServiceImpl.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripListDto.java
  src/main/java/com/lets/go/right/now/domain/trip/dto/TripPreviewDto.java
  src/main/java/com/lets/go/right/now/domain/trip/entity/Trip.java
  src/main/java/com/lets/go/right/now/domain/trip/service/TripServiceImpl.java
  src/main/java/com/lets/go/right/now/domain/tripMember/repository/TripMemberRepository.java
Labels: :rotating_light: Fix, :sparkles: Feat
